name: grouped_buttons
description: A simple package that makes grouping Checkboxes and Radio Buttons much easier.
version: 1.0.4
homepage: https://github.com/akshathjain/grouped_buttons

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
